export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const LOGIN_SINGLE_REQUEST = 'LOGIN_SINGLE_REQUEST'
export const LOGIN_SINGLE_SUCCESS = 'LOGIN_SINGLE_SUCCESS'
export const LOGIN_SINGLE_FAILED = 'LOGIN_SINGLE_FAILED'